// End-to-end lifecycle tests for SavedSearchStore — exercises the
// full draft → chat → promote → clear / abandon-and-GC flows that
// underpin the InsightAI History feature.
//
// Each test is named after the user-visible scenario it locks down:
//
//   • Bug 1 — FAB chat turns asked BEFORE the user taps Save are
//     persisted under the same draft id, so they appear in the saved
//     entry's history when the user later opens it from History.
//
//   • Bug 2 — After Save → Clear, the saved row is preserved (NOT
//     hard-deleted by discardDraftIfAny) so the History badge keeps
//     showing it. A subsequent reopen of the app sees a clean Tutor
//     screen because the in-memory caches were cleared, but the row
//     itself survives in Drift.
//
//   • Bug 3 — A draft that the user neither saved nor cleared (closed
//     the app, came back hours later) is hard-deleted by [_runGc]
//     once it's older than 24 hours, together with its chat messages
//     and rolling summary.

import 'package:ai_nexus/core/services/saved_search_store.dart';
import 'package:ai_nexus/data/local/database/app_database.dart';
import 'package:ai_nexus/domain/entities/saved_search.dart';
import 'package:ai_nexus/domain/entities/tutor_entities.dart';
import 'package:drift/drift.dart' as drift;
import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';

const _stubResult = TavilySearchResponse(
  answer: 'a',
  query: 'q',
  results: <TavilyResultItem>[],
);

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  group('SavedSearchStore — UUID + lifecycle scenarios', () {
    late AppDatabase db;
    late SavedSearchStore store;

    setUp(() async {
      db = AppDatabase.forTesting(NativeDatabase.memory());
      store = SavedSearchStore.instance;
      store.debugResetForTests();
      store.init(db, null);
    });

    tearDown(() async {
      store.debugResetForTests();
      await db.close();
    });

    test(
        'UUID generated by startDraft survives the wire round-trip and is the '
        'same key the server uses for cross-device sync', () async {
      // Mimics the "save on Device A, read on Device B" round-trip.
      final draft = await store.startDraft(
        kind: SavedSearchKind.query,
        query: 'cricket scores',
        result: _stubResult,
      );
      // The id is a UUIDv4 — non-empty, well-formed — and the toJson
      // wire shape includes it under the canonical 'id' key.
      expect(draft.id, isNotEmpty);
      expect(RegExp(r'^[0-9a-f-]{36}$').hasMatch(draft.id), isTrue,
          reason: 'startDraft must allocate a UUIDv4');

      // Promote → server payload built from the same row carries the same id.
      await store.promoteToSaved(draft.id);
      final saved = await store.getById(draft.id);
      expect(saved, isNotNull);
      final wire = saved!.toJson();
      expect(wire['id'], equals(draft.id),
          reason: 'wire payload must preserve the local id verbatim');

      // The fromJson round-trip produces an entry with the same id —
      // this is exactly what `_pullIndexFromServer` does when Device B
      // receives the row from the cloud.
      final reconstructed = SavedSearchEntry.fromJson(wire);
      expect(reconstructed.id, equals(draft.id),
          reason:
              'fromJson must recover the same id so Drift upserts are idempotent across devices');
    });

    test(
        'Bug 1: chat turns appended BEFORE promote land in the saved entry\'s '
        'history (no backfill needed)', () async {
      // Step 1: result lands → startDraft creates an unpinned row.
      final draft = await store.startDraft(
        kind: SavedSearchKind.query,
        query: 'who won?',
        result: _stubResult,
      );
      final draftId = draft.id;

      // The History sheet must NOT show this row yet — it's still a draft.
      expect(await store.listAll(), isEmpty,
          reason: 'drafts must not leak into watchAll/listAll');
      expect(await store.isSaved(draftId), isFalse);

      // Step 2: user asks 3 follow-up questions in the FAB chat. The
      // FAB receives `savedSearchId: draftId` and mirrors every turn.
      await store.appendMessage(
        searchId: draftId,
        messageId: 'q1',
        role: 'user',
        text: 'first question',
      );
      await store.appendMessage(
        searchId: draftId,
        messageId: 'a1',
        role: 'assistant',
        text: 'first answer',
        model: 'gemini',
      );
      await store.appendMessage(
        searchId: draftId,
        messageId: 'q2',
        role: 'user',
        text: 'second question',
      );
      await store.appendMessage(
        searchId: draftId,
        messageId: 'a2',
        role: 'assistant',
        text: 'second answer',
      );
      await store.appendMessage(
        searchId: draftId,
        messageId: 'q3',
        role: 'user',
        text: 'third question',
      );
      await store.appendMessage(
        searchId: draftId,
        messageId: 'a3',
        role: 'assistant',
        text: 'third answer',
      );

      // All 6 chat rows are present in Drift, keyed under the draft id.
      expect(await store.loadMessages(draftId), hasLength(6));

      // Step 3: user closes the chat, then taps the bookmark.
      final promoted = await store.promoteToSaved(draftId);
      expect(promoted, isTrue);

      // Step 4: the entry now appears in History under the SAME id —
      // crucially, no new id was allocated, so all 6 chat rows are
      // still associated with it. A new device would get the entry
      // and (separately) pull the chats by the same id.
      final saved = await store.listAll();
      expect(saved, hasLength(1));
      expect(saved.single.id, equals(draftId));

      // Step 5: opening the saved entry from History → all turns visible.
      final history = await store.loadMessages(draftId);
      expect(history.map((m) => m.id), <String>[
        'q1', 'a1', 'q2', 'a2', 'q3', 'a3', // oldest-first
      ]);
    });

    test(
        'Bug 2: Save → Clear preserves the saved row (discardDraftIfAny is a '
        'no-op for pinned=true) so History keeps showing it', () async {
      // Save the search.
      final draft = await store.startDraft(
        kind: SavedSearchKind.query,
        query: 'q',
        result: _stubResult,
      );
      await store.promoteToSaved(draft.id);
      expect(await store.isSaved(draft.id), isTrue);

      // User taps Clear (X) on the result card. The Tutor screen calls
      // discardDraftIfAny on the active id; for a pinned=true row this
      // is explicitly a no-op so the History badge keeps showing it.
      final discarded = await store.discardDraftIfAny(draft.id);
      expect(discarded, isFalse,
          reason: 'discardDraftIfAny must NOT touch saved (pinned=true) rows');

      // Row is still saved + visible in History.
      expect(await store.isSaved(draft.id), isTrue);
      expect(await store.listAll(), hasLength(1));

      // Now contrast with a draft: discardDraftIfAny removes it cleanly.
      final draft2 = await store.startDraft(
        kind: SavedSearchKind.query,
        query: 'q2',
        result: _stubResult,
      );
      await store.appendMessage(
        searchId: draft2.id,
        messageId: 'm-d2',
        role: 'user',
        text: 'msg',
      );
      final discarded2 = await store.discardDraftIfAny(draft2.id);
      expect(discarded2, isTrue);
      expect(await store.getById(draft2.id), isNull);
      // Cascade: chat messages for the discarded draft are gone too.
      final left = await db.select(db.savedSearchChatMessages).get();
      expect(left.where((r) => r.searchId == draft2.id), isEmpty);
    });

    test(
        'Bug 3: a draft that has been abandoned for >24h is GC\'d together '
        'with its chat messages and summary', () async {
      // Seed a draft + chat + summary with a fake 25h-old timestamp so
      // the GC sweeper sees it as abandoned. We bypass startDraft here
      // because it always stamps `now` for updatedAt.
      final ts25h = DateTime.now()
          .toUtc()
          .subtract(const Duration(hours: 25))
          .toIso8601String();
      const draftId = 'abandoned-draft';
      await db.into(db.savedSearches).insert(
            SavedSearchesCompanion.insert(
              id: draftId,
              kind: SavedSearchKind.query,
              query: 'q',
              title: 't',
              responseType: SavedSearchResponseType.tavily,
              responseJson: '{}',
              savedAt: ts25h,
              updatedAt: ts25h,
              pinned: const drift.Value(false),
            ),
          );
      await db.into(db.savedSearchChatMessages).insert(
            SavedSearchChatMessagesCompanion.insert(
              id: 'orphan-msg',
              searchId: draftId,
              role: 'user',
              msgText: 'never saved',
              createdAt: ts25h,
            ),
          );
      await db.into(db.savedSearchChatSummaries).insert(
            SavedSearchChatSummariesCompanion.insert(
              searchId: draftId,
              summaryText: 'rolling summary',
              pairsCovered: 1,
              updatedAt: ts25h,
            ),
          );

      // Sanity: the row is in Drift but hidden from History (pinned=false).
      expect(await store.listAll(), isEmpty);
      expect(await store.getById(draftId), isNotNull);

      await store.debugRunGc();

      // GC reaped the draft + cascaded its chat messages + summary.
      expect(await store.getById(draftId), isNull);
      final messages = await db.select(db.savedSearchChatMessages).get();
      final summaries =
          await db.select(db.savedSearchChatSummaries).get();
      expect(messages.where((r) => r.searchId == draftId), isEmpty);
      expect(summaries.where((r) => r.searchId == draftId), isEmpty);
    });

    test(
        'Bug 3 corollary: a fresh draft (<24h) is preserved by GC so users '
        'who background mid-session don\'t lose their working state',
        () async {
      // A draft created 10 min ago — well within the 24h TTL.
      final freshDraft = await store.startDraft(
        kind: SavedSearchKind.query,
        query: 'q',
        result: _stubResult,
      );
      await store.appendMessage(
        searchId: freshDraft.id,
        messageId: 'm-fresh',
        role: 'user',
        text: 'in-progress',
      );

      await store.debugRunGc();

      expect(await store.getById(freshDraft.id), isNotNull,
          reason:
              'fresh drafts must survive GC — only abandoned (>24h) drafts go away');
      expect(await store.loadMessages(freshDraft.id), hasLength(1));
    });

    test(
        'promoting a draft is idempotent — second tap on bookmark while '
        'still in flight does not allocate a new id', () async {
      final draft = await store.startDraft(
        kind: SavedSearchKind.query,
        query: 'q',
        result: _stubResult,
      );
      final firstPromote = await store.promoteToSaved(draft.id);
      final secondPromote = await store.promoteToSaved(draft.id);

      expect(firstPromote, isTrue);
      expect(secondPromote, isFalse,
          reason:
              'second promote of an already-saved row should be a clear no-op');
      expect(await store.listAll(), hasLength(1),
          reason: 'still exactly one row in History — no duplicate');
      expect(await store.isSaved(draft.id), isTrue);
    });

    test(
        'appendMessage refuses to move a chat row across searchIds — protects '
        'a saved entry\'s history from re-mirror after Save → Clear → '
        'Re-search of the same query', () async {
      // Scenario: user searches "X" → save → clear → search "X" again.
      // The in-memory FAB cache replays the SAME message ids against
      // the new draft id. Without the cross-searchId guard,
      // insertOnConflictUpdate would atomically move every message off
      // the saved entry, leaving its history empty.
      final saved = await store.startDraft(
        kind: SavedSearchKind.query,
        query: 'X',
        result: _stubResult,
      );
      await store.promoteToSaved(saved.id);
      await store.appendMessage(
        searchId: saved.id,
        messageId: 'msg-1',
        role: 'user',
        text: 'first ask',
      );
      await store.appendMessage(
        searchId: saved.id,
        messageId: 'msg-2',
        role: 'assistant',
        text: 'first answer',
      );

      // User clears + re-searches the same query → new draft id.
      final draft2 = await store.startDraft(
        kind: SavedSearchKind.query,
        query: 'X',
        result: _stubResult,
      );

      // The FAB cache replays the same message ids against the new draft.
      await store.appendMessage(
        searchId: draft2.id,
        messageId: 'msg-1',
        role: 'user',
        text: 'first ask',
      );
      await store.appendMessage(
        searchId: draft2.id,
        messageId: 'msg-2',
        role: 'assistant',
        text: 'first answer',
      );

      // Saved entry's history is INTACT — both messages are still
      // associated with the original saved id.
      final savedMsgs = await store.loadMessages(saved.id);
      expect(savedMsgs.map((m) => m.id), <String>['msg-1', 'msg-2'],
          reason:
              'cross-searchId guard must keep msg-1, msg-2 on the saved entry');

      // The new draft has NO chat rows (the replays were correctly skipped).
      expect(await store.loadMessages(draft2.id), isEmpty,
          reason:
              'replays from the in-memory cache must NOT be ingested under a new draft id');
    });

    test(
        'concurrent draft + Save (Path C race) → discardDraftIfAny prunes the '
        'orphaned draft so History stays clean', () async {
      // Mimics: user taps Save before the draft\'s Drift insert returns.
      // The UI takes Path C and creates a brand-new pinned=true row;
      // when the draft insert finally completes, the UI calls
      // discardDraftIfAny on the orphan to clean up immediately
      // instead of waiting for 24 h GC.
      final fastSave = await store.saveResult(
        kind: SavedSearchKind.query,
        query: 'q',
        result: _stubResult,
      );
      // Simulate the (delayed) draft completing while a saved row already
      // exists — this is exactly what _ensureActiveDraft now does when it
      // detects _activeSearchId was already populated.
      final orphan = await store.startDraft(
        kind: SavedSearchKind.query,
        query: 'q',
        result: _stubResult,
      );
      expect(orphan.id, isNot(equals(fastSave.id)));

      // Tutor screen calls discardDraftIfAny(orphan.id) on the lost-race
      // path — the orphan must vanish without touching the saved row.
      final discarded = await store.discardDraftIfAny(orphan.id);
      expect(discarded, isTrue);
      expect(await store.getById(orphan.id), isNull);

      // The saved row is unaffected — exactly one entry in History.
      expect(await store.listAll(), hasLength(1));
      expect((await store.listAll()).single.id, equals(fastSave.id));
    });
  });
}
