-keep class app.ainexus.ai_nexus.sms.** { *; }
-keep class app.ainexus.ai_nexus.ExpenseWidget** { *; }
-keep class app.ainexus.ai_nexus.SearchWidget** { *; }
-keep class app.ainexus.ai_nexus.WidgetBootReceiver { *; }
-keep class com.ryanheise.** { *; }
-keep class com.google.mlkit.vision.text.** { *; }
-keep class com.google.mlkit.vision.text.chinese.** { *; }
-keep class com.google.mlkit.vision.text.devanagari.** { *; }
-keep class com.google.mlkit.vision.text.japanese.** { *; }
-keep class com.google.mlkit.vision.text.korean.** { *; }
-dontwarn com.google.mlkit.vision.text.**
